"""add_missing_via_account_id_index

Revision ID: b948fad901ba
Revises: e07294f508ba
Create Date: 2026-02-23 06:11:34.458406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b948fad901ba'
down_revision: Union[str, Sequence[str], None] = 'e07294f508ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_budget_posts_via_account_id'), 'budget_posts', ['via_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_posts_via_account_id'), table_name='budget_posts')
    # ### end Alembic commands ###
