"""create accounts table

Revision ID: d83f85ee70e7
Revises: 1745f80b2c67
Create Date: 2026-02-04 12:40:41.179362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd83f85ee70e7'
down_revision: Union[str, Sequence[str], None] = '1745f80b2c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('normal', 'savings', 'loan', name='account_purpose'), nullable=False),
    sa.Column('datasource', sa.Enum('bank', 'credit', 'cash', 'virtual', name='account_datasource'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('starting_balance', sa.BigInteger(), nullable=False),
    sa.Column('can_go_negative', sa.Boolean(), nullable=False),
    sa.Column('needs_coverage', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_budget_id'), 'accounts', ['budget_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_budget_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
